version: 2

jobs:
  deploy-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy Docker tags
          command: ./build.sh

workflows:
  version: 2
  deploy:
    triggers:
      - schedule:
          cron: "*/10 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy-docker
