version: 2

jobs:
  deploy-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy Docker images
          command: ./build.sh

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-docker:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
  update:
    triggers:
      - schedule:
          cron: "0,10,20,30,40,50 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy-docker
